import { Inter, Poppins , Quicksand } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });
const poppins= Poppins({subsets: ["latin"],
weight:['100','200','300','400','500']})




const quick = Quicksand({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className,poppins.className)}>{children}</body>
    </html>
  );
}
